/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package SEAss1;

import java.io.Reader;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.File;


public class App
{
	public static void main(String[] args) throws IOException
	{
		int flag=0;
		System.out.println("Enter username and password");
		Scanner username = new Scanner(System.in);
		Scanner password = new Scanner(System.in);
		BufferedReader br = new BufferedReader(new FileReader("C:\\Civil Career\\Summer term 2022\\1- Software Engineering\\Ass 2\\SE-Project-try2\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\app\\src\\main\\resources\\Credentials.csv"));
		String uname = username.next();
		String pw = password.next();
		String line;
		
    	while ( (line = br.readLine()) != null ) 
		{
       		String[] values = line.split(",");
       	 	if(uname.equals(values[0]) && pw.equals(values[1]) && uname.equals("admin") && pw.equals("admin"))
			{
       	 		flag=1;
       	 		App.Adminfunc();
            	break;
        	}
       	 	
			else if((uname.equals(values[0]) && pw.equals(values[1])))
			{
				flag=1;
				App.Userfunc(uname);
				break;
			}
			else
			{
				continue;
			}
		}
    	if(flag==0)
    	{
    		System.out.println("You are not a valid user! Try again!");
    	}
    	
		username.close();
		password.close();
		br.close();
	}
	
	public static  void Adminfunc() throws IOException
	{
		System.out.println("Admin Logged in \nEnter 1 to display user's leave requests");
		System.out.println("Enter 2 to Logout");
    	Scanner number = new Scanner(System.in);
		String num = number.next();
		File rfile = new File("C:\\Civil Career\\Summer term 2022\\1- Software Engineering\\Ass 2\\SE-Project-try2\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\app\\src\\main\\resources\\book.csv");
		BufferedReader br = new BufferedReader(new FileReader(rfile));
		File file = new File("C:\\Civil Career\\Summer term 2022\\1- Software Engineering\\Ass 2\\SE-Project-try2\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\app\\src\\main\\resources\\temp.csv");
		if(!file.exists())
			file.createNewFile();
		FileWriter filew= new FileWriter(file.getAbsoluteFile());
		BufferedWriter decision = new BufferedWriter(filew);
		String line;
		if (num.equals("1")) ;
		{
			while((line = br.readLine()) != null) 
			{
				String[] values = line.split(",");
				if(values[2].equals("Not Decided")) 
				{
					System.out.print("Available leave request from " + values[0] +", number of hours requested: "+ values[1] + "\n");
					System.out.println("Enter your decision ? (yes or no)");
					Scanner input = new Scanner(System.in);
					String in = input.next();
					decision.write(values[0] + "," + values[1] + "," + in+ "\n");
					// this a close from the decision function //
					
				}
				
			}
			boolean success = file.renameTo(rfile);
			System.out.println(success);
			decision.close();
		}
		
	}
	public static void Userfunc(String uname) throws IOException
	{	 
//		int temp = 0;
//		while(.hasNextLine()) {
			System.out.println("User Logged in \nEnter 1 to display total working hours");
			System.out.println("Enter 2 for requesting leave");
			System.out.println("Enter 3 to Logout");
	    	Scanner number = new Scanner(System.in);
			String num = number.next();
			BufferedReader br = new BufferedReader(new FileReader("C:\\Civil Career\\Summer term 2022\\1- Software Engineering\\Ass 2\\SE-Project-try2\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\app\\src\\main\\resources\\Credentials.csv"));
			String line;
			if (num.equals("1")) 
			{
				while((line = br.readLine()) != null) 
				{
					String[] values = line.split(",");
					if(values[0].equals(uname)) 
					{
						System.out.print("Total working hours " + values[2]);
					}
				}
			}
			else if(num.equals("2")) 
			{	
				System.out.println("Enter leave request in hours: ");
				Scanner work_hours = new Scanner(System.in);
				String wh = work_hours.next();
				FileWriter fw = new FileWriter("C:\\Civil Career\\Summer term 2022\\1- Software Engineering\\Ass 2\\SE-Project-try2\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\SE-Project-ac199bf9917c77a06c698758b28e2f74a933753f\\app\\src\\main\\resources\\book.csv",true);
				BufferedWriter storing = new BufferedWriter(fw);
				storing.write(uname+","+wh+","+"Not Decided"+"\n");
				System.out.println("Info sent to Admin \nPlease wait for approval \nSigned out");
				work_hours.close();
				storing.close();
			}
			else if (num.equals("3")) 
			{
//				temp = 1;
				System.out.println("Logged out");
			}
//	}
			number.close();
	}
	
	
}
